// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzmxtGGaeL8is4WPiRZJ1bbj2oaoBOPQ',
    appId: '1:171972718220:web:8840ac22770869de2155a9',
    messagingSenderId: '171972718220',
    projectId: 'college-bell-system-26e92',
    authDomain: 'college-bell-system-26e92.firebaseapp.com',
    databaseURL: 'https://college-bell-system-26e92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-bell-system-26e92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv9g03hkge4ysd8RqC0hlnzOLTPQuzJ3M',
    appId: '1:171972718220:android:c8368c98594d4d7d2155a9',
    messagingSenderId: '171972718220',
    projectId: 'college-bell-system-26e92',
    databaseURL: 'https://college-bell-system-26e92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-bell-system-26e92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Q7V4w2Fz9Vq4vyXVmIMUmmPHQwlnXrQ',
    appId: '1:171972718220:ios:44ff55d4b12da89b2155a9',
    messagingSenderId: '171972718220',
    projectId: 'college-bell-system-26e92',
    databaseURL: 'https://college-bell-system-26e92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-bell-system-26e92.firebasestorage.app',
    iosBundleId: 'com.example.collegeBell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Q7V4w2Fz9Vq4vyXVmIMUmmPHQwlnXrQ',
    appId: '1:171972718220:ios:44ff55d4b12da89b2155a9',
    messagingSenderId: '171972718220',
    projectId: 'college-bell-system-26e92',
    databaseURL: 'https://college-bell-system-26e92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-bell-system-26e92.firebasestorage.app',
    iosBundleId: 'com.example.collegeBell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgzmxtGGaeL8is4WPiRZJ1bbj2oaoBOPQ',
    appId: '1:171972718220:web:e7aa6238f172df052155a9',
    messagingSenderId: '171972718220',
    projectId: 'college-bell-system-26e92',
    authDomain: 'college-bell-system-26e92.firebaseapp.com',
    databaseURL: 'https://college-bell-system-26e92-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'college-bell-system-26e92.firebasestorage.app',
  );

}